<?xml version="1.0" encoding="UTF-8"?><testrun name="test" project="JackarooGame" tests="252" started="252" failures="34" errors="35" ignored="0">
  <testsuite name="test.Milestone1PublicTests" time="0.343">
    <testcase name="testBoardInstanceVariablehSafeZonesOfTypeArrayListOfSafeZone" classname="test.Milestone1PublicTests" time="0.031"/>
    <testcase name="testCardFileInDeckOfType" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testBurnerCardConstructorInitialization" classname="test.Milestone1PublicTests" time="0.016">
      <failure>java.lang.AssertionError: Exception argument type mismatch occured while creating a burner card&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at test.Milestone1PublicTests.testBurnerCardConstructorInitialization(Milestone1PublicTests.java:945)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testConstructorWild" classname="test.Milestone1PublicTests" time="0.0">
      <failure>java.lang.AssertionError: Missing constructor with String and String and BoardManager and GameManager  parameters in Wild class.&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at org.junit.Assert.assertTrue(Assert.java:41)&#13;
	at org.junit.Assert.assertFalse(Assert.java:64)&#13;
	at test.Milestone1PublicTests.testConstructorExists(Milestone1PublicTests.java:5217)&#13;
	at test.Milestone1PublicTests.testConstructorWild(Milestone1PublicTests.java:899)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testConstructorSplitOutOfRangeException" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testCardInstanceVariableNameIsPresent" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testClassIsAbstractGameException" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testBoardInstanceVariableTrackIsFinal" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testPlayerInstanceVariableMarblesGetterLogic" classname="test.Milestone1PublicTests" time="0.015"/>
    <testcase name="testConstructorIllegalSwapException" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testGameInstanceVariableTurnNOGetter" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testInvalidMarbleExceptionConstructorInitializationCheck" classname="test.Milestone1PublicTests" time="0.0">
      <failure>java.lang.AssertionError: Class InvalidMarbleException should have the instance variable "detailMessage".&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at test.Milestone1PublicTests.testExceptionConstructorInitialization(Milestone1PublicTests.java:4041)&#13;
	at test.Milestone1PublicTests.testInvalidMarbleExceptionConstructorInitializationCheck(Milestone1PublicTests.java:3936)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testClassFiveExists" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testCurrentPlayerIndexInGameType" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testGetterForInstanceVariableSuitDoesNotExistInWeaponSubClasses" classname="test.Milestone1PublicTests" time="0.016"/>
    <testcase name="testGameInstanceVariableBoardNoSetter" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testIllegalMovementExceptionConstructorInitialization" classname="test.Milestone1PublicTests" time="0.0">
      <failure>java.lang.AssertionError: Class IllegalMovementException should have the instance variable "detailMessage".&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at test.Milestone1PublicTests.testExceptionConstructorInitialization(Milestone1PublicTests.java:4041)&#13;
	at test.Milestone1PublicTests.testIllegalMovementExceptionConstructorInitialization(Milestone1PublicTests.java:3957)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testGameInstanceVariableBoardIsFinal" classname="test.Milestone1PublicTests" time="0.0">
      <failure>java.lang.AssertionError: board should be final&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at org.junit.Assert.assertTrue(Assert.java:41)&#13;
	at test.Milestone1PublicTests.testInstanceVariableIsFinal(Milestone1PublicTests.java:5026)&#13;
	at test.Milestone1PublicTests.testGameInstanceVariableBoardIsFinal(Milestone1PublicTests.java:550)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testAssignTrapExistanceInClassBoard" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testConstructorInvalidCardException" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testGameInstanceVariableFirePitIsPrivate" classname="test.Milestone1PublicTests" time="0.0">
      <failure>java.lang.AssertionError: The "firePit" instance variable in class Game should not be accessed outside that class.&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at org.junit.Assert.assertTrue(Assert.java:41)&#13;
	at test.Milestone1PublicTests.testInstanceVariableIsPrivate(Milestone1PublicTests.java:5004)&#13;
	at test.Milestone1PublicTests.testGameInstanceVariableFirePitIsPrivate(Milestone1PublicTests.java:580)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testGameInstanceVariableFirePitPresent" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testTrapInCellSetterLogic2" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testConstructorCannotDiscardException" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testCellTypeEnumValues" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testKingCardConstructorInitialization" classname="test.Milestone1PublicTests" time="0.0">
      <error>java.lang.IllegalArgumentException: argument type mismatch&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at java.lang.reflect.Constructor.newInstance(Unknown Source)&#13;
	at test.Milestone1PublicTests.testKingCardConstructorInitialization(Milestone1PublicTests.java:2327)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testGetterLogicForDescriptionInClassStandard" classname="test.Milestone1PublicTests" time="0.0">
      <error>java.lang.IllegalArgumentException: argument type mismatch&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at java.lang.reflect.Constructor.newInstance(Unknown Source)&#13;
	at test.Milestone1PublicTests.testGetterLogicForDescriptionInClassStandard(Milestone1PublicTests.java:2645)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testBoardInstanceVariableTrackGetterLogic" classname="test.Milestone1PublicTests" time="0.0">
      <error>java.lang.IllegalArgumentException: argument type mismatch&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at java.lang.reflect.Constructor.newInstance(Unknown Source)&#13;
	at test.Milestone1PublicTests.testBoardInstanceVariableTrackGetterLogic(Milestone1PublicTests.java:3396)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testConstructorSevenExists" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testColourEnumValues" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testBoardConstructorInitializationSplittingDisctanceCorrect" classname="test.Milestone1PublicTests" time="0.0">
      <error>java.lang.IllegalArgumentException: argument type mismatch&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at java.lang.reflect.Constructor.newInstance(Unknown Source)&#13;
	at test.Milestone1PublicTests.testBoardConstructorInitializationSplittingDisctanceCorrect(Milestone1PublicTests.java:3550)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testInvalidCardExceptionConstructorInitialization" classname="test.Milestone1PublicTests" time="0.0">
      <failure>java.lang.AssertionError: Class InvalidCardException should have the instance variable "detailMessage".&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at test.Milestone1PublicTests.testExceptionConstructorInitialization(Milestone1PublicTests.java:4041)&#13;
	at test.Milestone1PublicTests.testInvalidCardExceptionConstructorInitialization(Milestone1PublicTests.java:3915)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testDrawCardsInDeckShufflesCards" classname="test.Milestone1PublicTests" time="0.0">
      <failure>java.lang.AssertionError: error occured while testing drawCards method check the console argument type mismatch&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at test.Milestone1PublicTests.testDrawCardsInDeckShufflesCards(Milestone1PublicTests.java:1902)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testCellInstanceVariableCellTypeIsPrivate" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testPlayerInstanceVariableNameGetterLogic" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testDrawCardsInDeckReturnsFourCards" classname="test.Milestone1PublicTests" time="0.0">
      <failure>java.lang.AssertionError: error occured while testing drawCards method check the console argument type mismatch&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at test.Milestone1PublicTests.testDrawCardsInDeckReturnsFourCards(Milestone1PublicTests.java:1778)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testMarbleConstructorInitialization" classname="test.Milestone1PublicTests" time="0.032"/>
    <testcase name="testMarbleInstanceVariableColourIsPrivate" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testCardsPoolInDeckOfType" classname="test.Milestone1PublicTests" time="0.015"/>
    <testcase name="testCardsFileInDeckIsStatic" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testSafeZoneConstructorInitializationColour" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testGameInstanceVariableFirePitGetterLogic" classname="test.Milestone1PublicTests" time="0.0">
      <error>java.lang.IllegalArgumentException: argument type mismatch&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at java.lang.reflect.Constructor.newInstance(Unknown Source)&#13;
	at test.Milestone1PublicTests.testGameInstanceVariableFirePitGetterLogic(Milestone1PublicTests.java:697)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testBoardInstanceVariableSplitDistanceOfTypeInt" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testSafeZoneInstanceVariableColourNoSetter" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testConstructorJackExists" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testConstructorSaver" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testSaverCardExists" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testGameConstructorInitializationFirePit" classname="test.Milestone1PublicTests" time="0.0">
      <failure>java.lang.AssertionError: The constructor of the Game class should initialize the instance variable "firePit" correctly. expected:&lt;[]&gt; but was:&lt;null&gt;&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at org.junit.Assert.failNotEquals(Assert.java:834)&#13;
	at org.junit.Assert.assertEquals(Assert.java:118)&#13;
	at test.Milestone1PublicTests.testGameConstructorInitialization(Milestone1PublicTests.java:4158)&#13;
	at test.Milestone1PublicTests.testGameConstructorInitializationFirePit(Milestone1PublicTests.java:766)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testGameClassImplementsGameManagerInterface" classname="test.Milestone1PublicTests" time="0.0">
      <failure>java.lang.AssertionError: Game should implement GameManager&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at org.junit.Assert.assertTrue(Assert.java:41)&#13;
	at test.Milestone1PublicTests.testClassImplementsInterface(Milestone1PublicTests.java:4760)&#13;
	at test.Milestone1PublicTests.testGameClassImplementsGameManagerInterface(Milestone1PublicTests.java:532)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testPlayerInstanceVariableHandGetterExists" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testCardInstanceVariableNameisFinal" classname="test.Milestone1PublicTests" time="0.0">
      <failure>java.lang.AssertionError: The name instance variable in class Card should be final&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at org.junit.Assert.assertTrue(Assert.java:41)&#13;
	at test.Milestone1PublicTests.testCardInstanceVariableNameisFinal(Milestone1PublicTests.java:2550)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testClassIsSubclassGameException" classname="test.Milestone1PublicTests" time="0.0">
      <failure>java.lang.AssertionError: GameException class should be a subclass from Exception. expected:&lt;class java.lang.Exception&gt; but was:&lt;class java.lang.Object&gt;&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at org.junit.Assert.failNotEquals(Assert.java:834)&#13;
	at org.junit.Assert.assertEquals(Assert.java:118)&#13;
	at test.Milestone1PublicTests.testClassIsSubclass(Milestone1PublicTests.java:4675)&#13;
	at test.Milestone1PublicTests.testClassIsSubclassGameException(Milestone1PublicTests.java:3757)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testLoadCardPoolInDeckisStatic" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testGameInstanceVariablePlayersIsFinal" classname="test.Milestone1PublicTests" time="0.0">
      <failure>java.lang.AssertionError: players should be final&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at org.junit.Assert.assertTrue(Assert.java:41)&#13;
	at test.Milestone1PublicTests.testInstanceVariableIsFinal(Milestone1PublicTests.java:5026)&#13;
	at test.Milestone1PublicTests.testGameInstanceVariablePlayersIsFinal(Milestone1PublicTests.java:568)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testConstructorCannotFieldException" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testCardInstanceVariableSuitiFinal" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testColourValues" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testLoadCardPoolInDeckReadingCSVLoadingStandardCards1Rank" classname="test.Milestone1PublicTests" time="0.0">
      <error>java.io.FileNotFoundException: Cards.csv (The system cannot find the file specified)&#13;
	at java.io.FileInputStream.open0(Native Method)&#13;
	at java.io.FileInputStream.open(Unknown Source)&#13;
	at java.io.FileInputStream.&lt;init&gt;(Unknown Source)&#13;
	at java.io.FileInputStream.&lt;init&gt;(Unknown Source)&#13;
	at java.io.FileReader.&lt;init&gt;(Unknown Source)&#13;
	at test.Milestone1PublicTests.savingCardsCSV(Milestone1PublicTests.java:4349)&#13;
	at test.Milestone1PublicTests.testLoadCardPoolInDeckReadingCSVLoadingStandardCards1Rank(Milestone1PublicTests.java:1555)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testTestingfiveIsSubClassOfStandrad" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testEmptyConstructorIllegalDestroyException" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testSafeZoneInstanceVariableCellsNoSetter" classname="test.Milestone1PublicTests" time="0.016"/>
    <testcase name="testPlayerInstanceVariableMarblesGetterExists" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testQueenCardConstructorInitialization" classname="test.Milestone1PublicTests" time="0.0">
      <error>java.lang.IllegalArgumentException: argument type mismatch&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at java.lang.reflect.Constructor.newInstance(Unknown Source)&#13;
	at test.Milestone1PublicTests.testQueenCardConstructorInitialization(Milestone1PublicTests.java:2365)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testGameInstanceVariableTurnIsPrivate" classname="test.Milestone1PublicTests" time="0.0">
      <failure>java.lang.AssertionError: The "turn" instance variable in class Game should not be accessed outside that class.&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at org.junit.Assert.assertTrue(Assert.java:41)&#13;
	at test.Milestone1PublicTests.testInstanceVariableIsPrivate(Milestone1PublicTests.java:5004)&#13;
	at test.Milestone1PublicTests.testGameInstanceVariableTurnIsPrivate(Milestone1PublicTests.java:614)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testEmptyConstructorActionException" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testSetterForInstanceVariableRankDoesNotExistInAnyClass" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testSafeZoneInstanceVariableColourGetterLogic" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testCannotDiscardExceptionConstructorInitialization" classname="test.Milestone1PublicTests" time="0.0">
      <failure>java.lang.AssertionError: Class CannotDiscardException should have the instance variable "detailMessage".&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at test.Milestone1PublicTests.testExceptionConstructorInitialization(Milestone1PublicTests.java:4041)&#13;
	at test.Milestone1PublicTests.testCannotDiscardExceptionConstructorInitialization(Milestone1PublicTests.java:4012)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testCardInstanceVariableDescriptionisFinal" classname="test.Milestone1PublicTests" time="0.0">
      <failure>java.lang.AssertionError: The description instance variable in class Card should be final&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at org.junit.Assert.assertTrue(Assert.java:41)&#13;
	at test.Milestone1PublicTests.testCardInstanceVariableDescriptionisFinal(Milestone1PublicTests.java:2556)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testSaverIsSubClassOfWild" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testConstructorAceExists" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testTrapInCellSetterLogic" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testWildCardIsAnAbstractClass" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testSafeZoneInstanceVariableCellsIsPrivate" classname="test.Milestone1PublicTests" time="0.015"/>
    <testcase name="testCellInstanceVariableTrapIsPrivate" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testGetterLogicForSuiteInClassStandard" classname="test.Milestone1PublicTests" time="0.0">
      <error>java.lang.IllegalArgumentException: argument type mismatch&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at java.lang.reflect.Constructor.newInstance(Unknown Source)&#13;
	at test.Milestone1PublicTests.testGetterLogicForSuiteInClassStandard(Milestone1PublicTests.java:2691)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testFiveCardConstructorInitialization" classname="test.Milestone1PublicTests" time="0.0">
      <error>java.lang.IllegalArgumentException: argument type mismatch&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at java.lang.reflect.Constructor.newInstance(Unknown Source)&#13;
	at test.Milestone1PublicTests.testFiveCardConstructorInitialization(Milestone1PublicTests.java:2479)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testClassIsSubclassActionException" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testConstructorBurner" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testSafeZoneConstructorInitializationCells" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testCellTypeInCellSetterExists" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testEmptyConstructorSplitOutOfRangeException" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testMarbleInstanceVariableColourIsFinal" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testGameInstanceVariableCurrentPlayerIndexNoSetter" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testBoardConstructorInitializationGameManagerCorrect" classname="test.Milestone1PublicTests" time="0.0">
      <error>java.lang.IllegalArgumentException: argument type mismatch&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at java.lang.reflect.Constructor.newInstance(Unknown Source)&#13;
	at test.Milestone1PublicTests.testBoardConstructorInitializationGameManagerCorrect(Milestone1PublicTests.java:3575)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testLoadCardPoolInDeckThrowsIOException" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testGameInstanceVariableBoardIsPrivate" classname="test.Milestone1PublicTests" time="0.0">
      <failure>java.lang.AssertionError: The "board" instance variable in class Game should not be accessed outside that class.&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at org.junit.Assert.assertTrue(Assert.java:41)&#13;
	at test.Milestone1PublicTests.testInstanceVariableIsPrivate(Milestone1PublicTests.java:5004)&#13;
	at test.Milestone1PublicTests.testGameInstanceVariableBoardIsPrivate(Milestone1PublicTests.java:545)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testPlayerInstanceVariableColourSetterIsAbsent" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testGameConstructorInitializationPlayersColours" classname="test.Milestone1PublicTests" time="0.0">
      <error>java.lang.IllegalArgumentException: argument type mismatch&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at java.lang.reflect.Constructor.newInstance(Unknown Source)&#13;
	at test.Milestone1PublicTests.testGameConstructorInitializationPlayersColours(Milestone1PublicTests.java:1928)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testBoardInstanceVariableSafeZonesSetterIsAbsent" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testPlayerConstructorInitializationSelectedMarblesCorrect" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testAssignTrapIsPrivateInClassBoard" classname="test.Milestone1PublicTests" time="0.0">
      <failure>java.lang.AssertionError: AssignTrapCell method should be private&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at org.junit.Assert.assertTrue(Assert.java:41)&#13;
	at test.Milestone1PublicTests.testAssignTrapIsPrivateInClassBoard(Milestone1PublicTests.java:3737)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testGameConstructorInitializationPlayersNames" classname="test.Milestone1PublicTests" time="0.016">
      <error>java.lang.IllegalArgumentException: argument type mismatch&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at java.lang.reflect.Constructor.newInstance(Unknown Source)&#13;
	at test.Milestone1PublicTests.testGameConstructorInitializationPlayersNames(Milestone1PublicTests.java:789)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testPlayerInstanceVariableSelectedCardOfTypeCard" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testGameInstanceVariableCurrentPlayerIndexIsFinal" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testBoardInstanceVariableTrackSetterIsAbsent" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testCardsPoolInDeckGetterIsAbsent" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testCellConstructorInitialization" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testCardInstanceVariablBoardManagerIsPresent" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testGameConstructorInitializationHandPlayers" classname="test.Milestone1PublicTests" time="0.0">
      <error>java.lang.NullPointerException&#13;
	at test.Milestone1PublicTests.testGameConstructorInitializationHandPlayers(Milestone1PublicTests.java:1990)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testTenCardConstructorInitialization" classname="test.Milestone1PublicTests" time="0.0">
      <error>java.lang.IllegalArgumentException: argument type mismatch&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at java.lang.reflect.Constructor.newInstance(Unknown Source)&#13;
	at test.Milestone1PublicTests.testTenCardConstructorInitialization(Milestone1PublicTests.java:2403)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testConstructorKingExists" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testLoadCardPoolInDeckReadingCSVLoadingMixCards" classname="test.Milestone1PublicTests" time="0.0">
      <error>java.io.FileNotFoundException: Cards.csv (The system cannot find the file specified)&#13;
	at java.io.FileInputStream.open0(Native Method)&#13;
	at java.io.FileInputStream.open(Unknown Source)&#13;
	at java.io.FileInputStream.&lt;init&gt;(Unknown Source)&#13;
	at java.io.FileInputStream.&lt;init&gt;(Unknown Source)&#13;
	at java.io.FileReader.&lt;init&gt;(Unknown Source)&#13;
	at test.Milestone1PublicTests.savingCardsCSV(Milestone1PublicTests.java:4349)&#13;
	at test.Milestone1PublicTests.testLoadCardPoolInDeckReadingCSVLoadingMixCards(Milestone1PublicTests.java:1296)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testEmptyConstructorCannotDiscardException" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testConstructorStandardExists" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testCPUInstanceVariableBoardManagerIsPresent" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testSafeZoneInstanceVariableCellsPresent" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testPlayerInstanceVariableSelectedCardSetterIsAbsent" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testBoardInstanceVariableSplitDistanceSetterLogic" classname="test.Milestone1PublicTests" time="0.015">
      <error>java.lang.IllegalArgumentException: argument type mismatch&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at java.lang.reflect.Constructor.newInstance(Unknown Source)&#13;
	at test.Milestone1PublicTests.testBoardInstanceVariableSplitDistanceSetterLogic(Milestone1PublicTests.java:3520)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testGameManagerIsAnInterface" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testIllegalSwapExceptionConstructorInitialization" classname="test.Milestone1PublicTests" time="0.0">
      <failure>java.lang.AssertionError: Class IllegalSwapException should have the instance variable "detailMessage".&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at test.Milestone1PublicTests.testExceptionConstructorInitialization(Milestone1PublicTests.java:4041)&#13;
	at test.Milestone1PublicTests.testIllegalSwapExceptionConstructorInitialization(Milestone1PublicTests.java:3969)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testDescriptionGetter" classname="test.Milestone1PublicTests" time="0.0">
      <failure>java.lang.AssertionError: The "description" instance variable in class Card is a READ variable.&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at org.junit.Assert.assertTrue(Assert.java:41)&#13;
	at test.Milestone1PublicTests.testGetterMethodExistsInClass(Milestone1PublicTests.java:5065)&#13;
	at test.Milestone1PublicTests.testDescriptionGetter(Milestone1PublicTests.java:2573)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testBoardInstanceVariableSplitDistanceGetterLogic" classname="test.Milestone1PublicTests" time="0.0">
      <error>java.lang.IllegalArgumentException: java.lang.ClassCastException@238259ab&#13;
	at sun.reflect.GeneratedConstructorAccessor4.newInstance(Unknown Source)&#13;
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at java.lang.reflect.Constructor.newInstance(Unknown Source)&#13;
	at test.Milestone1PublicTests.testBoardInstanceVariableSplitDistanceGetterLogic(Milestone1PublicTests.java:3489)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testClassIsSubclassIllegalSwapException" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testGetterLogicForNameInClassStandard" classname="test.Milestone1PublicTests" time="0.0">
      <error>java.lang.IllegalArgumentException: java.lang.ClassCastException@4ab64081&#13;
	at sun.reflect.GeneratedConstructorAccessor4.newInstance(Unknown Source)&#13;
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at java.lang.reflect.Constructor.newInstance(Unknown Source)&#13;
	at test.Milestone1PublicTests.testGetterLogicForNameInClassStandard(Milestone1PublicTests.java:2607)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testBoardInstanceVariableSplitDistanceGetterExists" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testStandardCardRankModifiers1" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testBoardClassExists" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testGameConstructorInitializationBoardMangers" classname="test.Milestone1PublicTests" time="0.0">
      <error>java.lang.NullPointerException&#13;
	at test.Milestone1PublicTests.testGameConstructorInitializationBoardMangers(Milestone1PublicTests.java:2124)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testPlayerInstanceVariableSelectedMarblesGetterIsAbsent" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testPlayerInstanceVariableMarblesIsPresent" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testEmptyConstructorIllegalMovementException" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testPlayerInstanceVariableMarblesIsPrivate" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testClassIsSubclassIllegalMovementException" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testPlayerInstanceVariableColourIsFinal" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testTestingsevenIsSubClassOfStandrad" classname="test.Milestone1PublicTests" time="0.016"/>
    <testcase name="testLoadCardPoolInDeckReadingCSVLoadingMixCards2" classname="test.Milestone1PublicTests" time="0.0">
      <error>java.io.FileNotFoundException: Cards.csv (The system cannot find the file specified)&#13;
	at java.io.FileInputStream.open0(Native Method)&#13;
	at java.io.FileInputStream.open(Unknown Source)&#13;
	at java.io.FileInputStream.&lt;init&gt;(Unknown Source)&#13;
	at java.io.FileInputStream.&lt;init&gt;(Unknown Source)&#13;
	at java.io.FileReader.&lt;init&gt;(Unknown Source)&#13;
	at test.Milestone1PublicTests.savingCardsCSV(Milestone1PublicTests.java:4349)&#13;
	at test.Milestone1PublicTests.testLoadCardPoolInDeckReadingCSVLoadingMixCards2(Milestone1PublicTests.java:1356)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testSetterForInstanceVariableNameDoesNotExistInAnyClass" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testPlayerInstanceVariableColourIsPresent" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testClassIsSubclassInvalidCardException" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testConstructorGameException" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testPlayerConstructorInitializationMarblesCorrect" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testNameCardsLoadCardPoolInDeckReadingCSVLoadingWildCards" classname="test.Milestone1PublicTests" time="0.0">
      <error>java.io.FileNotFoundException: Cards.csv (The system cannot find the file specified)&#13;
	at java.io.FileInputStream.open0(Native Method)&#13;
	at java.io.FileInputStream.open(Unknown Source)&#13;
	at java.io.FileInputStream.&lt;init&gt;(Unknown Source)&#13;
	at java.io.FileInputStream.&lt;init&gt;(Unknown Source)&#13;
	at java.io.FileReader.&lt;init&gt;(Unknown Source)&#13;
	at test.Milestone1PublicTests.savingCardsCSV(Milestone1PublicTests.java:4349)&#13;
	at test.Milestone1PublicTests.testNameCardsLoadCardPoolInDeckReadingCSVLoadingWildCards(Milestone1PublicTests.java:1119)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testClassBurnerExists" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testRankGetter" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testCPUConstructorExists" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testSafeZoneInstanceVariableColourIsFinal" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testCardsFileInDeckIsFinal" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testCardsPoolInDeckIsPrivate" classname="test.Milestone1PublicTests" time="0.016"/>
    <testcase name="testGameInstanceVariableBoardGetterExists" classname="test.Milestone1PublicTests" time="0.0">
      <failure>java.lang.AssertionError: The "board" instance variable in class Game is a READ variable.&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at org.junit.Assert.assertTrue(Assert.java:41)&#13;
	at test.Milestone1PublicTests.testGetterMethodExistsInClass(Milestone1PublicTests.java:5065)&#13;
	at test.Milestone1PublicTests.testGameInstanceVariableBoardGetterExists(Milestone1PublicTests.java:622)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testBoardConstructorInitializationTrackCorrect" classname="test.Milestone1PublicTests" time="0.0">
      <error>java.lang.IllegalArgumentException: java.lang.ClassCastException@28beeb2f&#13;
	at sun.reflect.GeneratedConstructorAccessor4.newInstance(Unknown Source)&#13;
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at java.lang.reflect.Constructor.newInstance(Unknown Source)&#13;
	at test.Milestone1PublicTests.testBoardConstructorInitializationTrackCorrect(Milestone1PublicTests.java:3601)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testClassTenExists" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testPlayerInstanceVariableNameSetterIsAbsent" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testStandardCardConstructorInitialization" classname="test.Milestone1PublicTests" time="0.0">
      <error>java.lang.IllegalArgumentException: java.lang.ClassCastException@15b414f0&#13;
	at sun.reflect.GeneratedConstructorAccessor4.newInstance(Unknown Source)&#13;
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at java.lang.reflect.Constructor.newInstance(Unknown Source)&#13;
	at test.Milestone1PublicTests.testStandardCardConstructorInitialization(Milestone1PublicTests.java:2288)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testBoardInstanceVariableGameManagerOfTypeGameManager" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testCellInstanceVariableCellTypeGetterLogic" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testEmptyConstructorGameException" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testCPUInstanceVariableBoardManagerIsFinal" classname="test.Milestone1PublicTests" time="0.0">
      <failure>java.lang.AssertionError: boardManager should be final&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at org.junit.Assert.assertTrue(Assert.java:41)&#13;
	at test.Milestone1PublicTests.testInstanceVariableIsFinal(Milestone1PublicTests.java:5026)&#13;
	at test.Milestone1PublicTests.testCPUInstanceVariableBoardManagerIsFinal(Milestone1PublicTests.java:3231)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testCodeCardsLoadCardPoolInDeckReadingCSVLoadingWildCards" classname="test.Milestone1PublicTests" time="0.0">
      <error>java.io.FileNotFoundException: Cards.csv (The system cannot find the file specified)&#13;
	at java.io.FileInputStream.open0(Native Method)&#13;
	at java.io.FileInputStream.open(Unknown Source)&#13;
	at java.io.FileInputStream.&lt;init&gt;(Unknown Source)&#13;
	at java.io.FileInputStream.&lt;init&gt;(Unknown Source)&#13;
	at java.io.FileReader.&lt;init&gt;(Unknown Source)&#13;
	at test.Milestone1PublicTests.savingCardsCSV(Milestone1PublicTests.java:4349)&#13;
	at test.Milestone1PublicTests.testCodeCardsLoadCardPoolInDeckReadingCSVLoadingWildCards(Milestone1PublicTests.java:1174)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testCardDescriptionModifiers4" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testDrawCardsInDeckisStatic" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testCellInstanceVariableMarbleGetterLogic" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testgetSplitDistanceInBoardManagerInterface" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testCannotDiscardExceptionConstructorInitializationCheck" classname="test.Milestone1PublicTests" time="0.0">
      <failure>java.lang.AssertionError: Class CannotDiscardException should have the instance variable "detailMessage".&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at test.Milestone1PublicTests.testExceptionConstructorInitialization(Milestone1PublicTests.java:4041)&#13;
	at test.Milestone1PublicTests.testCannotDiscardExceptionConstructorInitializationCheck(Milestone1PublicTests.java:4022)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testSafeZoneInstanceVariableColourGetterExists" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testMarbleInCellSetterLogic" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testTypeOfMarbleInCell" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testGameInstanceVariableCurrentPlayerIndexNOGetter" classname="test.Milestone1PublicTests" time="0.015"/>
    <testcase name="testGameInstanceVariableTurnPresent" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testGameInstanceVariableFirePitIsFinal" classname="test.Milestone1PublicTests" time="0.0">
      <failure>java.lang.AssertionError: firePit should be final&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at org.junit.Assert.assertTrue(Assert.java:41)&#13;
	at test.Milestone1PublicTests.testInstanceVariableIsFinal(Milestone1PublicTests.java:5026)&#13;
	at test.Milestone1PublicTests.testGameInstanceVariableFirePitIsFinal(Milestone1PublicTests.java:585)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testPlayerInstanceVariableSelectedMarblesIsPrivate" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testGameInstanceVariablePlayersGetterExists" classname="test.Milestone1PublicTests" time="0.0">
      <failure>java.lang.AssertionError: The "players" instance variable in class Game is a READ variable.&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at org.junit.Assert.assertTrue(Assert.java:41)&#13;
	at test.Milestone1PublicTests.testGetterMethodExistsInClass(Milestone1PublicTests.java:5065)&#13;
	at test.Milestone1PublicTests.testGameInstanceVariablePlayersGetterExists(Milestone1PublicTests.java:638)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testClassIsSubclassCannotFieldException" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testIsCardAnAbstractClass" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testPlayerInstanceVariablehHandOfTypeArrayListOfCard" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testCardsFileInDeckExistance" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testTestingJackIsSubClassOfStandrad" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testBoardInstanceVariablehTrackOfTypeArrayListOfCell" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testGameInstanceVariablePlayersPresent" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testCannotFieldExceptionConstructorInitialization" classname="test.Milestone1PublicTests" time="0.0">
      <failure>java.lang.AssertionError: Class CannotFieldException should have the instance variable "detailMessage".&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at test.Milestone1PublicTests.testExceptionConstructorInitialization(Milestone1PublicTests.java:4041)&#13;
	at test.Milestone1PublicTests.testCannotFieldExceptionConstructorInitialization(Milestone1PublicTests.java:4001)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testPlayerInstanceVariableSelectedCardGetterLogic" classname="test.Milestone1PublicTests" time="0.0">
      <error>java.lang.IllegalArgumentException: java.lang.ClassCastException@41600e9a&#13;
	at sun.reflect.GeneratedConstructorAccessor4.newInstance(Unknown Source)&#13;
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at java.lang.reflect.Constructor.newInstance(Unknown Source)&#13;
	at test.Milestone1PublicTests.testPlayerInstanceVariableSelectedCardGetterLogic(Milestone1PublicTests.java:2917)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testCPUConstructorInitialization" classname="test.Milestone1PublicTests" time="0.0">
      <error>java.lang.IllegalArgumentException: java.lang.ClassCastException@211b37a0&#13;
	at sun.reflect.GeneratedConstructorAccessor4.newInstance(Unknown Source)&#13;
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at java.lang.reflect.Constructor.newInstance(Unknown Source)&#13;
	at test.Milestone1PublicTests.testCPUConstructorInitialization(Milestone1PublicTests.java:3293)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testPlayerInstanceVariableNameIsFinal" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testSplitOutOfRangeExceptionConstructorInitializationCheck" classname="test.Milestone1PublicTests" time="0.0">
      <failure>java.lang.AssertionError: Class SplitOutOfRangeException should have the instance variable "detailMessage".&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at test.Milestone1PublicTests.testExceptionConstructorInitialization(Milestone1PublicTests.java:4041)&#13;
	at test.Milestone1PublicTests.testSplitOutOfRangeExceptionConstructorInitializationCheck(Milestone1PublicTests.java:3947)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testTrapInCellGetterExists" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testBoardManagerModifier" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testPlayerInstanceVariableSelectedMarblesOfTypeArrayList" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testGameInstanceVariableFirePitNoSetter" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testMarbleInCellSetterExists" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testGameConstructorInitializationTurn" classname="test.Milestone1PublicTests" time="0.032"/>
    <testcase name="testBoardConstructorInitializationSafeZonesCorrect" classname="test.Milestone1PublicTests" time="0.0">
      <error>java.lang.IllegalArgumentException: java.lang.ClassCastException@16a5e0c7&#13;
	at sun.reflect.GeneratedConstructorAccessor4.newInstance(Unknown Source)&#13;
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at java.lang.reflect.Constructor.newInstance(Unknown Source)&#13;
	at test.Milestone1PublicTests.testBoardConstructorInitializationSafeZonesCorrect(Milestone1PublicTests.java:3686)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testPlayerConstructorInitializationHandCorrect" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testPlayerInstanceVariableMarblesOfTypeArrayListOfMarbles" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testBoardInGameType" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testGameInstanceVariablePlayersGetterLogic" classname="test.Milestone1PublicTests" time="0.0">
      <error>java.lang.NoSuchMethodException: engine.Game.getPlayers()&#13;
	at java.lang.Class.getDeclaredMethod(Unknown Source)&#13;
	at test.Milestone1PublicTests.testGetterMethodLogic(Milestone1PublicTests.java:4830)&#13;
	at test.Milestone1PublicTests.testGameInstanceVariablePlayersGetterLogic(Milestone1PublicTests.java:664)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testClassCardExists" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testColourInMarbleType" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testSafeZoneInstanceVariableCellsGetterExists" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testLoadCardPoolInDeckReadingCSVLoadingStandardCards1" classname="test.Milestone1PublicTests" time="0.0">
      <error>java.io.FileNotFoundException: Cards.csv (The system cannot find the file specified)&#13;
	at java.io.FileInputStream.open0(Native Method)&#13;
	at java.io.FileInputStream.open(Unknown Source)&#13;
	at java.io.FileInputStream.&lt;init&gt;(Unknown Source)&#13;
	at java.io.FileInputStream.&lt;init&gt;(Unknown Source)&#13;
	at java.io.FileReader.&lt;init&gt;(Unknown Source)&#13;
	at test.Milestone1PublicTests.savingCardsCSV(Milestone1PublicTests.java:4349)&#13;
	at test.Milestone1PublicTests.testLoadCardPoolInDeckReadingCSVLoadingStandardCards1(Milestone1PublicTests.java:1457)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testLoadCardPoolInDeckReadingCSVLoadingStandardCards2" classname="test.Milestone1PublicTests" time="0.0">
      <error>java.io.FileNotFoundException: Cards.csv (The system cannot find the file specified)&#13;
	at java.io.FileInputStream.open0(Native Method)&#13;
	at java.io.FileInputStream.open(Unknown Source)&#13;
	at java.io.FileInputStream.&lt;init&gt;(Unknown Source)&#13;
	at java.io.FileInputStream.&lt;init&gt;(Unknown Source)&#13;
	at java.io.FileReader.&lt;init&gt;(Unknown Source)&#13;
	at test.Milestone1PublicTests.savingCardsCSV(Milestone1PublicTests.java:4349)&#13;
	at test.Milestone1PublicTests.testLoadCardPoolInDeckReadingCSVLoadingStandardCards2(Milestone1PublicTests.java:1654)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testPlayerInstanceVariableNameIsPrivate" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testColourInSafeZoneType" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testInvalidMarbleExceptionConstructorInitialization" classname="test.Milestone1PublicTests" time="0.0">
      <failure>java.lang.AssertionError: Class InvalidMarbleException should have the instance variable "detailMessage".&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at test.Milestone1PublicTests.testExceptionConstructorInitialization(Milestone1PublicTests.java:4041)&#13;
	at test.Milestone1PublicTests.testInvalidMarbleExceptionConstructorInitialization(Milestone1PublicTests.java:3926)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testCellConstructorExists" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testBoardInstanceVariableSafeZonesIsPresent" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testBoardInstanceVariableSafeZonesIsPrivate" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testBoardInstanceVariableGameManagerGetterIsAbsent" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testClassJackExists" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testCellTypeIsEnum" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testTestingQueenIsSubClassOfStandrad" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testConstructorfourExists" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testPlayerInstanceVariableHandIsPresent" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testPlayerInstanceVariableHandIsPrivate" classname="test.Milestone1PublicTests" time="0.015"/>
    <testcase name="testCardInstanceVariablRankIsPresent" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testBoardInstanceVariableGameManagerIsFinal" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testEmptyConstructorInvalidCardException" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testBurnerIsSubClassOfWild" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testMarbleInstanceVariableColourGetterLogic" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testPlayerInstanceVariableSelectedMarblesIsFinal" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testFrequencyCardsLoadCardPoolInDeckReadingCSVLoadingWildCards" classname="test.Milestone1PublicTests" time="0.0">
      <error>java.io.FileNotFoundException: Cards.csv (The system cannot find the file specified)&#13;
	at java.io.FileInputStream.open0(Native Method)&#13;
	at java.io.FileInputStream.open(Unknown Source)&#13;
	at java.io.FileInputStream.&lt;init&gt;(Unknown Source)&#13;
	at java.io.FileInputStream.&lt;init&gt;(Unknown Source)&#13;
	at java.io.FileReader.&lt;init&gt;(Unknown Source)&#13;
	at test.Milestone1PublicTests.savingCardsCSV(Milestone1PublicTests.java:4349)&#13;
	at test.Milestone1PublicTests.testFrequencyCardsLoadCardPoolInDeckReadingCSVLoadingWildCards(Milestone1PublicTests.java:1231)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testCellInstanceVariableMarbleGetterExists" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testGameInstanceVariableCurrentPlayerIndexPresent" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testBoardInstanceVariableSplitDistanceSetterExists" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testCardsPoolInDeckIsStatic" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testMarbleInstanceVariableColourGetterExists" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testGameInstanceVariablePlayersNoSetter" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testPlayerConstructorInitialization" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testConstructorActionException" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testCellInstanceVariableTrapPresent" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testMarbleInstanceVariableColourNoSetter" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testCardsFileInDeckValue" classname="test.Milestone1PublicTests" time="0.0">
      <failure>
        <expected>Cards.csv</expected>
        <actual>../Cards.csv</actual>org.junit.ComparisonFailure: expected:&lt;[]Cards.csv&gt; but was:&lt;[../]Cards.csv&gt;&#13;
	at org.junit.Assert.assertEquals(Assert.java:115)&#13;
	at org.junit.Assert.assertEquals(Assert.java:144)&#13;
	at test.Milestone1PublicTests.testCardsFileInDeckValue(Milestone1PublicTests.java:1010)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testFirePitInGameType" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testTypeOfCellTypeInCell" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testClassAceExists" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testBoardImplementsBoardManager" classname="test.Milestone1PublicTests" time="0.0">
      <failure>java.lang.AssertionError: Board should implement BoardManager&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at org.junit.Assert.assertTrue(Assert.java:41)&#13;
	at test.Milestone1PublicTests.testBoardImplementsBoardManager(Milestone1PublicTests.java:3323)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testCPUSubToPlayer" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testSuitGetter" classname="test.Milestone1PublicTests" time="0.016"/>
    <testcase name="testBoardInstanceVariableSafeZonesGetterExists" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testGetterForInstanceVariableRankDoesNotExistInWeaponSubClasses" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testSuitIsEnum" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testPlayerInstanceVariableHandSetterLogic" classname="test.Milestone1PublicTests" time="0.0">
      <error>java.lang.IllegalArgumentException: java.lang.ClassCastException@67f9d0b9&#13;
	at sun.reflect.GeneratedConstructorAccessor4.newInstance(Unknown Source)&#13;
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at java.lang.reflect.Constructor.newInstance(Unknown Source)&#13;
	at test.Milestone1PublicTests.testPlayerInstanceVariableHandSetterLogic(Milestone1PublicTests.java:3080)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testSevenCardConstructorInitialization" classname="test.Milestone1PublicTests" time="0.0">
      <error>java.lang.IllegalArgumentException: java.lang.ClassCastException@7d0f9eb3&#13;
	at sun.reflect.GeneratedConstructorAccessor4.newInstance(Unknown Source)&#13;
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at java.lang.reflect.Constructor.newInstance(Unknown Source)&#13;
	at test.Milestone1PublicTests.testSevenCardConstructorInitialization(Milestone1PublicTests.java:2441)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testCardFileInDeckGetterIsAbsent" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testBoardInstanceVariableTrackIsPresent" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testBoardInstanceVariableTrackIsPrivate" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testGetterForInstanceVariableNameDoesNotExistInWeaponSubClasses" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testPlayerInstanceVariableHandGetterLogic" classname="test.Milestone1PublicTests" time="0.0">
      <error>java.lang.IllegalArgumentException: java.lang.ClassCastException@5f81d6a1&#13;
	at sun.reflect.GeneratedConstructorAccessor4.newInstance(Unknown Source)&#13;
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at java.lang.reflect.Constructor.newInstance(Unknown Source)&#13;
	at test.Milestone1PublicTests.testPlayerInstanceVariableHandGetterLogic(Milestone1PublicTests.java:3041)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testClassIsAbstractInvalidSelectionException" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testDrawCardsInDeckRemovedCardsCards" classname="test.Milestone1PublicTests" time="0.0">
      <failure>java.lang.AssertionError: error occured while testing drawCards method check the console java.lang.ClassCastException@4a448a5&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at test.Milestone1PublicTests.testDrawCardsInDeckRemovedCardsCards(Milestone1PublicTests.java:1839)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testIllegalDestroyExceptionConstructorInitializationCheck" classname="test.Milestone1PublicTests" time="0.0">
      <failure>java.lang.AssertionError: Class IllegalDestroyException should have the instance variable "detailMessage".&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at test.Milestone1PublicTests.testExceptionConstructorInitialization(Milestone1PublicTests.java:4041)&#13;
	at test.Milestone1PublicTests.testIllegalDestroyExceptionConstructorInitializationCheck(Milestone1PublicTests.java:3991)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testWildCardExists" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testPlayerInstanceVariableColourGetterLogicCase1" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testTestingStandardIsSubClassOfCard" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testIllegalSwapExceptionConstructorInitializationCheck" classname="test.Milestone1PublicTests" time="0.0">
      <failure>java.lang.AssertionError: Class IllegalSwapException should have the instance variable "detailMessage".&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at test.Milestone1PublicTests.testExceptionConstructorInitialization(Milestone1PublicTests.java:4041)&#13;
	at test.Milestone1PublicTests.testIllegalSwapExceptionConstructorInitializationCheck(Milestone1PublicTests.java:3979)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testCellInstanceVariableMarbleIsPrivate" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testGameConstructorInitializationGameMangers" classname="test.Milestone1PublicTests" time="0.0">
      <error>java.lang.NullPointerException&#13;
	at test.Milestone1PublicTests.testGameConstructorInitializationGameMangers(Milestone1PublicTests.java:2057)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testCardsPoolInDeckSetterIsAbsent" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testConstructorIllegalDestroyException" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testSafeZoneInstanceVariableColourPresent" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testCPUInstanceVariableBoardManagerSetterIsAbsent" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testSafeZoneInstanceVariableCellsIsFinal" classname="test.Milestone1PublicTests" time="0.0"/>
    <testcase name="testClassKingExists" classname="test.Milestone1PublicTests" time="0.0"/>
  </testsuite>
</testrun>
